apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}

  # Pod manifest
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:

      # We only need these when pulling from a private registry
      imagePullSecrets:
      - name: vmgitent

      containers:
      - name: frontend

        # image from Private registry
        # image: vmgitent.iskratel.si:4567/voje/docker-registry/frontend:0.0.1

        # image from DockerHub
        image: voje/frontend:0.1.0

        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
