apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}

  # Pod manifest
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: vmgitent
      containers:
      - image: vmgitent.iskratel.si:4567/voje/docker-registry/frontend:0.0.1
        name: frontend
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
