apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: vmgitent.iskratel.si:4567/voje/docker-registry/frontend:0.0.1
    name: frontend
    resources: {}
    env:
    - name: POD_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: vmgitent
